import AsyncStorage from "@react-native-async-storage/async-storage";

/* 

    OBJECTS

*/
//this stores every instance of the orders that the user had made
export type HistoryInstance = {
        name:string,
        garageName:string,
        date:Date,
        
        price: number
    }
    //this stores the unique name of the device, generated by firebase
export type Name = {
    name:string
}

/*

    OPERATIONS REGARDING HISTORY

*/
//this saves a history item in history
export const saveItem = async(item: HistoryInstance)=>{
    try {
        //this gets the existing data and appends a new item whenever the user orders something
        const existingData = await AsyncStorage.getItem("@history");
        const currentHistory :HistoryInstance[] = existingData ?JSON.parse(existingData):[];
        currentHistory.unshift(item);
        const historyStr = JSON.stringify(currentHistory);
        await AsyncStorage.setItem('@history',historyStr);
    }catch(e){
        console.log("Fail: "+ e);
    }
}
export const getItems = async () =>{
    try{
        //this simply retruns all of the users purchaces
        const existingData = await AsyncStorage.getItem('@history');
        
        return existingData ?JSON.parse(existingData):[];
    }catch(e){
        console.log("Fail: "+e);
        return [];
    }
}
/*

    OPERATIONS REGARDING THE FIREBASE NAME OF THE USER FOR NOTIFICATIONS

*/

//this saves the name of the device
export const saveName = async(item: Name)=>{
    try {
        const existingData = await AsyncStorage.getItem("@name");
        const currentName = existingData ?JSON.parse(existingData):[];
        currentName.unshift(item);
        const nameStr = JSON.stringify(currentName);
        await AsyncStorage.setItem('@name',nameStr);
    }catch(e){
        console.log("Fail: "+ e);
    }
}
//this return sthe name of the device, generated by firebase
export const getName = async () =>{
    try{
        const existingData = await AsyncStorage.getItem('@name');
        
        return existingData ?JSON.parse(existingData):'';
    }catch(e){
        console.log("Fail: "+e);
        return '';
    }
}